### ISSUE TITLE
config get appendfilename doesn't work

### ISSUE THREAD

**Issue by Kortenbach** [tporadowski/redis#10]
I test-drove this verion because I was having an issue with Redis version 3.2.100 running on Windows 10 64Bit. It seems that V4.0.2 alpha still has this issue:

My .conf file:
_# The name of the append only file (default: "appendonly.aof")
appendfilename appendonly.aof_

cli command: _config get ap*_
Returns:
_1) "appendfsync"
2) "everysec"
3) "appendonly"
4) "yes"_

Appendfilename is not listed. Is this a bug?

Redis version 4.0.2 running on Windows 10 64Bit

**Comment by tporadowski** [comment]
Looks like this (and probably others) config option has never been supported by [configGetCommand](https://github.com/antirez/redis/blob/84b281209a653f8afe5b106ab44d8339fd798823/src/config.c#L1211) (this is the function in current original Redis code that outputs reply for "CONFIG GET pattern").

**Comment by tporadowski** [comment]
I knew I saw this somewhere already ;) - antirez/redis#4753
