### ISSUE TITLE
Search module?

### ISSUE THREAD

**Issue by DankMemeGuy** [tporadowski/redis#101]
Not a bug, but there wasn't any other options:

Is there any way to add the RediSearch module? I use RedisInsight and when I click on any of the module options it tells me to install them, but I can't seem to find any Windows ones. Let me know if this doens't exist or I'm at the wrong place to ask.
 Thank you!

**Comment by tporadowski** [comment]
Modules are supported, but the main problem is that they need to be compiled under Windows to a DLL. They are written mostly with main Redis in mind (thus targeting mostly Linux), so they **may require** adjustments. So far I've managed to only port [RedisJSON](https://github.com/tporadowski/rejson) to test a real-life module in Redis for Windows, and I have no idea what effort it would be for any other module.
