### ISSUE TITLE
Keys * crashes CLI

### ISSUE THREAD

**Issue by Kortenbach** [tporadowski/redis#11]
Hi,

I have a DB size of 24730 hash keys:
Command: Keys * crashes the CLI
Command: Scan 0 returns the first x keys (OK)
Command: Keys A* returns the keys that start with A (OK)

It seems that if the CLI receives a long list of keys it will crash...

**Comment by Kortenbach** [comment]
Tried to repeat this with the "old" cli against the new Redis 4.0.2 --> CLI keeps crashing.
So, it seems not to be the CLI that is failing but Redis itself...

**Comment by tporadowski** [comment]
From what I've seen and read about "KEYS" command in general is that its usage is highly discouraged and basically I can observe the same (no way to list 100k+ keys that I have with that command). This is however working pretty fine under Linux (I've just tested some simple 50k+ keys), so indeed it might be some bug in the server.

**Comment by Kortenbach** [comment]
Hi @tporadowski,
Thanks for the quick reply!
I forgot to mention that this worked perfecly fine in the last official Windows release, so it's either someting in V4.0.2 or in this fork. I agree that you generally should not use "keys *" but since I was testdriving, I thought I should mention it.

**Comment by tporadowski** [comment]
I now know the reason why it's failing - it's an issue in Redis server. I have a working solution already, but I still need to see if this issue affects only Windows port or is a general one.

**Comment by tporadowski** [comment]
Thanks @Kortenbach for the report. This turned out to be quite important (sending back larger amounts of data to the client), so I will create a new release today.

**Comment by Kortenbach** [comment]
Thank you! I will start using it again. I stopt using it because I had another crash this week. This time the server was repeatedly crashing and restarting itself over and over. I believe it was after a flushdb. I will keep you posted...

**Comment by tporadowski** [comment]
4.0.2.1 released, please test it :)

**Comment by Kortenbach** [comment]
Issue is solved in V4.0.2.1Alpha

**Comment by Kortenbach** [comment]
I noticed a side-effect (?) in release 4.0.2.1: I can now edit my previous commands in the CLI by using the up/down arrow on my keyboard.

**Comment by tporadowski** [comment]
:) I fixed this issue "in the meantime", but didn't do a full release just for that - it was added as a side-download to first 4.0.2-alpha release. See commit 1d95d353 and antirez/redis#4536

**Comment by Kortenbach** [comment]
Super!

**Comment by tporadowski** [comment]
Yup, it was frustrating to type everything over and over again ;)
