### ISSUE TITLE
How to upgrade without loosing db

### ISSUE THREAD

**Issue by diplopito** [tporadowski/redis#120]
Hi Tomasz,

Thanks again for your great work. Question: Which is the best way to upgrade without loosing the Redis db?

Thanks in advance!

**Comment by tporadowski** [comment]
Have you had such a problem? As far as I know there is no special need to do anything here (apart from recommended backup like in any other database) - the upgrade is just stopping the process, replacing binaries, and starting it again - thus reading the database again from RDB/AOF. This could probably be different if there was a breaking change in RDB/AOF formats, but this case is likely covered in some Redis guide.

**Comment by diplopito** [comment]
It worked flawlessly: I haven't done an upgrade in a while and I forgot how simple it is, thanks again!
