### ISSUE TITLE
Update to 4.0.9 or newer? 

### ISSUE THREAD

**Issue by yinlin66** [tporadowski/redis#13]
It seems the latest stable version is 4.0.9 now. Any plan to update?

**Comment by tporadowski** [comment]
I try to keep track of what's going on in Redis and I am aware of a couple 4.0.x releases in the meantime, but so far I had no time to finish tasks planned for [beta milestone](https://github.com/tporadowski/redis/milestone/2)... I would rather like to finish those first (i.e. provide support for modules, update dependencies) and then try to keep the features/bugfixes up-to-date.
Summing up - yes, update to latest release is planned, though I can't say when exactly (probably within next 3-4 months).

**Comment by letrthang** [comment]
Thanks. 
I hope Microsoft aware about your contribution and giving some supporting for you.

**Comment by zls3434** [comment]
Thanks for work.
Hoping!

**Comment by ghd258** [comment]
Update to 4.0.11?

**Comment by tporadowski** [comment]
@ghd258 yes, eventually when 4.0.2 is up-to-date with original Redis 4.0.2 (pending: modules support, update of dependencies) then the next release will be an upgrade to the latest 4.0.x of Redis (4.0.9 was the latest at the time when this question was created).

**Comment by ghd258** [comment]
When will the official version be released?

**Comment by tporadowski** [comment]
@ghd258 What do you mean with "official"? I am working on reaching "beta" and then I can do a full "production" release, but Redis has never supported Windows so I don't think @antirez will make an "official" version available in the same way one can get Redis. As far as I remember even MSOpenTech's version was available for download from https://redis.io in "Unofficial" section.

**Comment by tporadowski** [comment]
Code base in `develop` branch is now synced with 4.0.14 of original Redis, after some clean up and testing - it should be ready for releasing in 2-3 weeks.

**Comment by tporadowski** [comment]
[Redis 4.0.14 for Windows](https://github.com/tporadowski/redis/releases/tag/v4.0.14) has just been released.
