### ISSUE TITLE
where is release.h

### ISSUE THREAD

**Issue by dexter-wan** [tporadowski/redis#131]
release.c compilation requires release.h
This file is not present in the entire project

**Comment by tporadowski** [comment]
That is correct, it is however described in main README of the repo:

> **Building from source code**
> 
> In order to build this project from source code you need to have:
> 
> 1. Visual Studio 2019 (i.e. Community Edition, version 16.2.5 or newer) with "C/C++ features" enabled,
> 1. Windows SDK 10,
> 1. [Git Bash](https://gitforwindows.org/) for Windows or [Cygwin](http://cygwin.com/) with Git - after cloning this repository you need to run `src/mkreleasehdr.sh` script that creates `src/release.h` with some information taken from Git; optionally you can create that file by hand.
