### ISSUE TITLE
It is recommended to release redis 6 version

### ISSUE THREAD

**Issue by yinbug** [tporadowski/redis#137]
It is recommended to release redis 6 version.
The official version of redis 6 has been out for a long time.

**Comment by zkteco-home** [comment]
Redis 7.0 Rc2 for windows has been released,you can try to test it,it is very stable. please visit zkteco-home/redis-windows

**Comment by zkteco-home** [comment]
redis 7.0 has many new features,so it is not recommended to use redis 6.0.

**Comment by yinbug** [comment]
ok , looking forward to the official release of redis 7.0 for windows

**Comment by liudonghua123** [comment]
official redis 7.0 has released. I would like to use this new version which has many new amazing features.

**Comment by yinbug** [comment]
Thank you for your guidance
