### ISSUE TITLE
Address WSA_IO_PENDING warnings in log files

### ISSUE THREAD

**Issue by MikeChristensen** [tporadowski/redis#14]
This is in reference to [this issue](https://github.com/antirez/redis/issues/3793), which seems to be specific to the Windows port of Redis.  We get about 2 of these warnings logged every second for each machine in our cluster.  There doesn't appear to be a way to turn them off without turning off all of logging.  This is causing an issue both due to hard disk space, as well as costing us money since we're using Splunk to index log files.  I'd love to see a way to suppress these warnings, or a work around for the issue.

**Comment by tporadowski** [comment]
Yes, it is specific to Windows port. It's logged with severity ```WARNING``` and indeed cannot be avoided without turning logging off completely. It is logged in ```src/cluster.c```: https://github.com/tporadowski/redis/blob/win-4.0.2/src/cluster.c#L2118-L2119

I am not sure about the purpose of this information, but we could:
  1. decrease its severity (to verbose or debug)
  1. remove it completely.

**Comment by tporadowski** [comment]
Ouch, now I know what you mean... I'm trying to reproduce an issue in cluster mode (#12) and it is indeed annoying and not really that much helpful - I will set it to use ```debug``` verbosity.

**Comment by tporadowski** [comment]
Resolved in 6262460fdff
