### ISSUE TITLE
rdb file wrong,cause program interupt and exit

### ISSUE THREAD

**Issue by wywdstc** [tporadowski/redis#15]
[1624] 11 Apr 17:16:20.480 # WSA_IO_PENDING writing to socket fd 186
[1624] 11 Apr 17:16:20.496 # WSA_IO_PENDING writing to socket fd 182
[1624] 11 Apr 17:16:20.527 # clusterWriteDone written 2568 fd 186
[1624] 11 Apr 17:16:20.558 # clusterWriteDone written 2568 fd 182
[1624] 11 Apr 17:16:23.371 # Short read or OOM loading DB. Unrecoverable error,
aborting now.
[1624] 11 Apr 17:16:23.402 # Internal error in RDB reading function at rdb.c:16
7 -> Unexpected EOF reading RDB file
[offset 0] Checking RDB file dump.rdb
[offset 28] AUX FIELD redis-ver = '4.0.2.2'
[offset 42] AUX FIELD redis-bits = '64'
[offset 54] AUX FIELD ctime = '1523437583'
[offset 66] AUX FIELD used-mem = '0'
[offset 84] AUX FIELD repl-stream-db = '0'
[offset 134] AUX FIELD repl-id = '6df0b53efe93c65443a5a1491f12281b9f75541f'
[offset 152] AUX FIELD repl-offset = '570220748'
[offset 168] AUX FIELD aof-preamble = '0'
[offset 170] Selecting DB ID 0

**Comment by wywdstc** [comment]
when i use redis-check-rdb:

F:\redis\Redis-x64-4.0.2.2\14229>redis-check-rdb dump.rdb
[offset 0] Checking RDB file dump.rdb
[offset 28] AUX FIELD redis-ver = '4.0.2.2'
[offset 42] AUX FIELD redis-bits = '64'
[offset 54] AUX FIELD ctime = '1523437583'
[offset 66] AUX FIELD used-mem = '0'
[offset 84] AUX FIELD repl-stream-db = '0'
[offset 134] AUX FIELD repl-id = '6df0b53efe93c65443a5a1491f12281b9f75541f'
[offset 152] AUX FIELD repl-offset = '570220748'
[offset 168] AUX FIELD aof-preamble = '0'
[offset 170] Selecting DB ID 0
--- RDB ERROR DETECTED ---
[offset 2864892912] Invalid LZF compressed string
[additional info] While doing: read-object-value
[additional info] Reading key 'taobao_145819333'
[additional info] Reading type 13 (hash-ziplist)
[info] 32888301 keys read
[info] 0 expires
[info] 0 already expired

F:\redis\Redis-x64-4.0.2.2\14229>

**Comment by tporadowski** [comment]
Issue not reproduced, ticket not active, so closing. We've also fixed several bugs in newer versions, so this might also be gone now.
