### ISSUE TITLE
integer is returning although the value is decimal

### ISSUE THREAD

**Issue by bybera** [tporadowski/redis#18]
My decimal.lua file 
```
local incomingVal = ARGV[1]

redis.call('hset', 'incomingVal:', 'strVal', incomingVal)
redis.call('hset', 'incomingVal:', 'numVal', tonumber(incomingVal))

local a = redis.call('hget', 'incomingVal:', 'strVal')
local b = redis.call('hget', 'incomingVal:', 'numVal')

return {a, b, tonumber(b)}
```

then redis command line
`$ redis-cli --eval decimal.lua 0 , 0.005`

and returns value ;
```
1) "0.005"
2) "0.0050000000000000001"
3) (integer) 0
```

why my decimal variable is an integer. I guess there is an error. what do you think?

**Comment by tporadowski** [comment]
Works as designed, please see documentation for [EVAL](https://redis.io/commands/eval).

> Also there are two important rules to note:
>
> Lua has a single numerical type, Lua numbers. There is no distinction between integers and floats. So we always convert Lua numbers into integer replies, removing the decimal part of the number if any. **If you want to return a float from Lua you should return it as a string**, exactly like Redis itself does (see for instance the ZSCORE command).
