### ISSUE TITLE
callstack print to log file

### ISSUE THREAD

**Issue by conghuawang** [tporadowski/redis#19]
there is a call stack print to log file, and bgrewriteaof failed:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
Redis version: 4.0.2.2
[5032] 18 Jun 11:42:15.018 # ------------------------------------------------
[5032] 18 Jun 11:42:15.018 # Fatal Error: Invalid integer encoding 0xFF #..\src\ziplist.c:320
[5032] 18 Jun 11:42:15.018 # ------------------------------------------------
[5032] 18 Jun 11:42:15.018 # --- EXCEPTION_ACCESS_VIOLATION
[5032] 18 Jun 11:42:15.018 # --- STACK TRACE
redis-server.exe!((null):0)(0x0014E410, 0x0014FF90, 0x00000000, 0x1400ECBE0)
redis-server.exe!((null):0)(0x0014E410, 0x00000000, 0x00000000, 0x7FF815B90000)
KERNELBASE.dll!UnhandledExceptionFilter((null):0)(0x140107EEC, 0x7FF82397C15C, 0x00000000, 0x00000000)
ntdll.dll!memset((null):0)(0x0014EB80, 0x0014F070, 0x1400EAD08, 0x0014F070)
ntdll.dll!_C_specific_handler((null):0)(0x00000000, 0x0014E580, 0x0014EB80, 0x00000000)
ntdll.dll!_chkstk((null):0)(0x0014E580, 0x0014EB80, 0x7FF82295AB10, 0x00000000)
ntdll.dll!RtlWalkFrameChain((null):0)(0x00000002, 0x00000008, 0x14012C728, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x14012C728, 0x140115C10, 0x00171200, 0x00008000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x14011F3FC, 0x00000002, 0x14012C728, 0x000000FF)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000002, 0x00000002, 0x00000019, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x7FCDB9AA9E3A, 0x14000B6EC, 0x00000000, 0x00000019)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0014F530, 0x00000019, 0x7FFFFFFFFFFFFFFF, 0x0014F5B8)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x02C09070, 0x0000001A, 0x02C09070, 0x7FCDB9AA9E01)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0014F690, 0x0014F5F9, 0x00000000, 0x00000007)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00582830, 0x00000006, 0x00000007, 0x00582830)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000008, 0x0014F820, 0xFFFFFFFFFFFFFFFE, 0x012A2760)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00EA0000, 0x00000005, 0x00000007, 0x1401AE1E8)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00582B30, 0x1401AE1E8)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000001, 0x00000001)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x7FF82085A580, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[5032] 18 Jun 11:42:15.019 # --- INFO OUTPUT

I checked the physical memeory:
redis occupy 2.8GB(use "info memory" command in redis-cli.exe)
physical memory remain: 6.5GB

why redis bgrewriteaof failed?

**Comment by tporadowski** [comment]
AOF file got apparently corrupted due to memory/page file issue, linking to #20.
