### ISSUE TITLE
rewrite aof failed

### ISSUE THREAD

**Issue by conghuawang** [tporadowski/redis#20]
when execute command "bgrewriteaof" in redis-cli.exe, error message print to log file:

[11896] 18 Jun 12:39:28.289 * Background append only file rewriting started by pid 18112
[18112] 18 Jun 12:39:28.407 # 
The Windows version of Redis reserves heap memory from the system paging file
for sharing with the forked process used for persistence operations.At this time there is insufficient contiguous free space available in the
system paging file. You may increase the size of the system paging file.
Sometimes a reboot will defragment the system paging file sufficiently for
this operation to complete successfully.

Redis can not continue. Exiting.
[11896] 18 Jun 12:39:28.494 # fork operation failed
[11896] 18 Jun 12:39:28.771 # Background AOF rewrite terminated by signal 1

But i check the memory, system has enough physical memory, show bellow:
![1](https://user-images.githubusercontent.com/16575549/41518479-4d6b7bce-72f5-11e8-8eee-039607300163.png)
![2](https://user-images.githubusercontent.com/16575549/41518488-52efeee0-72f5-11e8-9456-226d5a0d3352.png)

Does anybody have resolve the problem?

**Comment by tporadowski** [comment]
@conghuawang I'm afraid I can't help you more than what the message suggests. Please also refer to:
https://github.com/MicrosoftArchive/redis/wiki/Memory-Configuration-For-Redis-3.0#system-paging-file-size-requirements
https://github.com/MicrosoftArchive/redis/wiki/Memory-Configuration-For-Redis-3.0#preventing-redis-from-running-out-of-memory
as those chapters describe memory/paging file requirements.

**Comment by conghuawang** [comment]
@tporadowski 
Thank you for your reply. I just resolve the problem by fellow steps:
1. set windows pagefile to 2*physicMemory
2. set auto-aof-rewrite-percentage to very high, like 100000
3. write a program to rewrite aof manully at idle time
