### ISSUE TITLE
redis4.0 not work when l install 64bit in 32bit system 

### ISSUE THREAD

**Issue by deepbreath** [tporadowski/redis#21]
when l build 32bit msi it also not install 
![2](https://user-images.githubusercontent.com/15621942/42493825-ae2869c4-841e-11e8-8b0a-b79c8b2e6b20.png)

**Comment by tporadowski** [comment]
Hi @deepbreath, 32-bit version was not supported by MS OpenTech and I myself do not plan to support it. Feel free to make it work by yourself and submit a PR if you can make both 64/32 co-exist. Good luck!
