### ISSUE TITLE
Modify redisContextSetTimeout for Windows

### ISSUE THREAD

**Issue by SimHeonSeop** [tporadowski/redis#24]
See the MS site
https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt

The optval is a DWORD (DWORD value is millisecond)
This project needs to be modified for windows

= Proposal code =
#ifdef _WIN32

int redisContextSetTimeout(redisContext *c, const unsigned long tv) {
    if (setsockopt(c->fd, SOL_SOCKET, SO_RCVTIMEO, (char*)&tv, sizeof(tv)) == -1) {
        __redisSetErrorFromErrno(c, REDIS_ERR_IO, "setsockopt(SO_RCVTIMEO)");
        return REDIS_ERR;
    }
    if (setsockopt(c->fd, SOL_SOCKET, SO_SNDTIMEO, (char*)&tv, sizeof(tv)) == -1) {
        __redisSetErrorFromErrno(c, REDIS_ERR_IO, "setsockopt(SO_SNDTIMEO)");
        return REDIS_ERR;
    }
    return REDIS_OK;
}
#else
int redisContextSetTimeout(redisContext *c, const struct timeval tv) {
    if (setsockopt(c->fd,SOL_SOCKET,SO_RCVTIMEO,&tv,sizeof(tv)) == -1) {
        __redisSetErrorFromErrno(c,REDIS_ERR_IO,"setsockopt(SO_RCVTIMEO)");
        return REDIS_ERR;
    }
    if (setsockopt(c->fd,SOL_SOCKET,SO_SNDTIMEO,&tv,sizeof(tv)) == -1) {
        __redisSetErrorFromErrno(c,REDIS_ERR_IO,"setsockopt(SO_SNDTIMEO)");
        return REDIS_ERR;
    }
    return REDIS_OK;
}
#endif

**Comment by tporadowski** [comment]
Hi @SimHeonSeop,

Thanks for pointing this out. I guess just doing a cast like in your proposed version is not enough as the meaning of "timeval" and "DWORD" differ too much and Windows version needs to translate that ```tv``` to a DWORD.

**Comment by tporadowski** [comment]
I've just searched for usage of that function and it is used only in ```redisSetTimeout``` (hiredis) which in turn is only used in hiredis' tests (which are not included in solution). So your finding is still valid, but since it's not in use I will close this issue.
