### ISSUE TITLE
Wrong version? redis-server version shows 2.4.11-pre2

### ISSUE THREAD

**Issue by jetic83** [tporadowski/redis#27]
Checking the code out, building with Visual Studio works seamless, thank you!!
But the resulting redis-server.exe shows to be version 2.4.11-pre2.

![image](https://user-images.githubusercontent.com/11157551/46885185-3d28dc80-ce25-11e8-9731-aa3aae87f61b.png)

**Comment by tporadowski** [comment]
Which branch are you on? Main "win-4.0.2" has a completely different format for "--version", so you probably took an older 2.4.x :)

**Comment by jetic83** [comment]
Yes, this actually solved the problem, thanks a lot @tporadowski 

After changing the branch, the build was not completely seamless anymore for me: first it failed, since `release.h` was not present in the `/src` folder. After double click on `src/mkreleasehdr.sh`, the file was created and the following build worked as charm! 

Now, let's play with the new version! Thanks a lot!

**Comment by tporadowski** [comment]
This file is generated for Redis during build via Makefile and since it's a shell script - we'd need something else for Windows. I'm using Cygwin to run that script and didn't bother to include it in Visual Studio build process yet.
