### ISSUE TITLE
Is there a 5.0 version of windows redis?

### ISSUE THREAD

**Issue by zwl1619** [tporadowski/redis#28]
Is there a 5.0 version of windows redis?

**Comment by tporadowski** [comment]
Not yet, my plan is to finish porting 4.0.2, upgrade it to latest 4.0.x and then have a look at 5.x.

**Comment by aberbegall** [comment]
I guess it's worth to mention that until the version 5 of "Redis for windows" is available, there are alternatives:
* Windows 10 FCU users can enable [Windows Subsystem for Linux](https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-wsl-in-windows-10-fall-creators-update/), install and run POSIX Redis 5.0 on top of it.
* Install [POSIX Redis 5.0](http://download.redis.io/releases/redis-5.0.0.tar.gz) on cloud linux VM and connect using redis-cli (e.g "Redis for windows" or "Redis on windows"). This is the setup I'm using to play around with new redis streams feature on windows connected to a VM instance in Google Cloud Compute Engine.

**Comment by tporadowski** [comment]
@aberbegall: sure, those were always available, but the purpose of this fork is a native Windows version and as such 5.x is not available yet
