### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by israellot** [tporadowski/redis#29]
Not an issue, just wanted to say it's a great effort. Congratulations.

**Comment by israellot** [comment]
Another suggestion @tporadowski 

You could enumerate work items and leave them open for grab. I would be happy to help coding some of them at least. 

And finally, 
It's very hard to find this repository. Searching "redis windows" doesn't bring it on the list. Maybe you should change the naming and add more info to the description to make it more exposed.

**Comment by tporadowski** [comment]
Hi @israellot,

I will be more than happy if you can take a look at [TODO items](https://github.com/tporadowski/redis/labels/TODO) on the issues list, for the moment we have:

- #4 libraries in "deps" subfolder are still at the versions used for Redis 3.2 and they should be upgraded to the versions used in Redis 4.0.2
- #5 when upgrading MS OpenTech's version 3.2.100 to 4.0.2 I compared all of the source files for changes and copied over newer code of Redis 4.0.2, but there are some bigger code blocks enclosed within `#if _WIN32 ... #else ... #endif` that _may_ have not been fully updated. There _could_ be some Windows-specific rewrites of Redis' code that were overlooked and those changes from original Redis 4.0.2 may not have been added to those `#if _WIN32` blocks.
- #6 adding support for modules. I've already started it on branch [module-support](https://github.com/tporadowski/redis/tree/module-support) and got stuck a bit at converting/porting usage of unix sockets that are used for some sort of IPC with modules.

I guess only the last one (#6) is actually about some real coding ;)

Thanks for the suggestion to make this fork more visible - I will update the description and we'll see if it helps :)

**Comment by VoidMonk** [comment]
Great work @tporadowski 👍 Aiming for Redis 5? :)

**Comment by tporadowski** [comment]
@voidmonk yes, of course! :) But first I plan to make 4.0.2 a full port of Redis 4.0.2, then upgrade it to 4.0.11 and we're good to go for 5.x :)

**Comment by tporadowski** [comment]
@israellot in case you started working on any of the above - I've started upgrading dependencies (#4)

**Comment by israellot** [comment]
Thanks for the heads up @tporadowski ! 
So far I've cloned the project and started getting familiar with the windows port. 
Regarding checking win sections, maybe we should introduce a marker for each section checked?

**Comment by tporadowski** [comment]
@israellot it seems that MS Open Tech had an idea for this (using [`INDUCE_MERGE_CONFLICT`](https://github.com/tporadowski/redis/blob/win-4.0.2/src/Win32_Interop/Win32_Portability.h#L32) marker), but they didn't use it anywhere ;). If you're looking into #5 then maybe you could use it? (like in the example in that comment I linked earlier)

**Comment by israellot** [comment]
It seems that when you merged the code, your editor added whitespace on function definitions 
*func(a,b)* -> *func(a, b)* 
When trying to compare with antirez branches, it gets hard to spot differences. Any idea of how we can revert the code formatting without too much manual labor?

**Comment by tporadowski** [comment]
@israellot indeed, standard Visual Studio formatting kicked in, but to be honest - I find it more readable than the original code :). For merging I'm using [WinMerge](http://winmerge.org/) with option "White characters -> Ignore all", which makes it a bit easier. I suppose we have these options:

1. Go back to original formatting temporarily, compare and then apply VS formatting again. This would have to be done from time to time.
1. Go back to original formatting for good, adjust VS settings to conform to that and get used to it. This will ease all the future merging, but the part about _getting used to_ that formatting makes me wonder ;)
1. Apply VS formatting on all source files in this fork and before any merge also on original code (i.e. via some script) - this will let us keep the formatting more readable and make merging easier.

Personally I'm for option 3. Any other ideas?

**Comment by tporadowski** [comment]
I chatted with Salvatore yesterday about formatting and since he doesn't use any tools for that I guess options 1 and 2 are out.

**Comment by israellot** [comment]
I do agree that VS's formatting is more readable, but I honestly think that we shouldn't touch formatting on sections that we didn't touch the code. It's just easier. We can start reverting to original formatting little by little every time we touch and commit something. Soon we'll catch up, at least on the server project. Then it will become easier to merge antirez's commits on top of our codebase.

**Comment by tporadowski** [comment]
Then you'd have to disable automatic formatting on save, which I personally prefer, and use the formatting tool only in some sections (or even do the formatting yourself)... not so easy, but doable. I will look for some command-line C code beautifiers and see what they can do with original code and the one from this fork.

**Comment by israellot** [comment]
I personally never use auto format on save. I use Control-K-F to format sections I've worked on. 
But when porting other's projects I prefer not to touch their formatting, no matter how ugly that might be, in favor of making comparison tools lives easier. 
Another upside of not touching formatting is the ability to merge by picking commits directly from upstream, I guess that was the idea on MSOpenTech work.
If we always apply formatting to Antirez's branches, and apply the same to the port branch, that might work as well, just one step more that needs to be automated.
