### ISSUE TITLE
Incompatible with FOSS editors and IDE

### ISSUE THREAD

**Issue by ramlaxman** [tporadowski/redis#31]
This version is constantly crashing when I am using open source IDE and editors on Windows.

It includes [FastoNoSQL](https://fastonosql.com/), [FastoRedis](https://fastoredis.com/) and [Redis Desktop Manager](https://redisdesktop.com/).

**Comment by tporadowski** [comment]
@ramlaxman: thanks for information, but it would be far more helpful if you provided more details - which version of Redis for Windows you are running, what operations are causing it to crash and (most important) what Redis is reporting in its crash log.

**Comment by ramlaxman** [comment]
Sure. PFA inline:  
> 
> @ramlaxman: thanks for information, but it would be far more helpful if you provided more details - which version of Redis for Windows you are running,:

Redis 4.0.2.3 latest release
> what operations are causing it to crash 

Simply launching IDE and when it connects with Redis-server.

> and (most important) what Redis is reporting in it crash log.

Where to find it?

**Comment by tporadowski** [comment]
@ramlaxman you can find the logs here:
  1. when installed as service - either in Event Log ("Windows logs\Application", source ```redis```) or in ```server_log.txt``` file in installation folder (defaults to ```C:\Program Files\Redis```)
  1. if not found in the above - please start the Redis server from ```cmd.exe``` and it will report the crash information to console

FYI - I have downloaded FastoRedis and it worked without any problems.
