### ISSUE TITLE
Redis5.0 Windows Version 

### ISSUE THREAD

**Issue by linrb** [tporadowski/redis#33]
Redis5.0 Has Develop Plan?

**Comment by itransit** [comment]
I was looking forward to a jolly party for “Redis5.0 Windows Version” ！

**Comment by lefig** [comment]
Firstly can I just say how much appreciated is your work on Redis 4. 

Any news regarding when you get round to looking at Redis 5 would be outstanding. Can't wait to check out streams!
Best

**Comment by israellot** [comment]
Hi all, 
There's still work to do regarding the 4.0 branch, such as enabling modules. Unfortunately, the time available for working on it for the active developers here is very limited. Help would be much appreciated. 
Thanks!

**Comment by wjkhappy14** [comment]
1

**Comment by ByteRax** [comment]
+1

**Comment by maurosys** [comment]
to Redis5 there are https://www.memurai.com/

**Comment by tporadowski** [comment]
@israellot thanks for your efforts! We now have 4.0.14 released, so we can head towards 5.0 :). Feel free to push any changes directly to **develop** branch if you have some time for it!

**Comment by israellot** [comment]
great! 5.0 next milestone.
