### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by JHeLiu** [tporadowski/redis#36]
I would like to ask, I want to use it as the enterprise project to run it now reliable?

**Comment by tporadowski** [comment]
I know only about one company that is deploying this version in production for almost a year (as cache layer), so it would be best to hear what others are doing with it. The latest version from this repo passes all tests and I consider it stable enough for production, but it always depends on many factors and usage scenarios - I would thus recommend to give it a thorough testing first and if there is nothing special you need from versions 4.0.3+ of Redis then you're good to go (fixes from 4.0.3+ will be merged here as well, this is already in progress)

**Comment by JHeLiu** [comment]
@tporadowski  Thank you very much for your reply. It seems that your package did not get the signature, and I thought it could not be installed

**Comment by tporadowski** [comment]
For the moment I do not plan to invest on buying a code-signing certificate and even those I have seen for open source projects are not free, unfortunately.
On a side note related to this project's reliability - it has just reached [over 13k downloads](http://www.somsubhra.com/github-release-stats/?username=tporadowski&repository=redis), but I can't really say if that is going to help you decide :)
