### ISSUE TITLE
make redis windows. conf work 

### ISSUE THREAD

**Issue by wangeugene** [tporadowski/redis#38]
Your redis installer for windows is so easy to use! 
until when I wanna add the authentication ( add password)  to the service 
I tried 
modified  redis.windows.conf file ,add requireauth aaa
> redis-server --service-install redis.windows.conf --loglevel verbose
It prompted already installed,  
even after restart redis service, it won't work 
would you write a wiki to show how to do this for people new here?

**Comment by tporadowski** [comment]
Please read [AUTH command](https://redis.io/commands/auth) description as it mentions `requirepass` config option. Also you don't have to reinstall the service after changing the config file - a restart of Redis service is enough.
