### ISSUE TITLE
Github action example?

### ISSUE THREAD

**Issue by OskarPersson** [tporadowski/redis#45]
Are there any examples available for using this for testing in Github actions?

**Comment by tporadowski** [comment]
What would you like to achieve?

**Comment by OskarPersson** [comment]
I'm trying to migrate our CI solution (which requires Redis when testing from Travis to Github Actions). On Travis I could simply use docker to start redis on both Windows and Linux. Github Actions currently only supports Docker on Linux so I need another way to setup Redis on Windows

**Comment by tporadowski** [comment]
The easiest way is to unzip it from a ZIP package as installation is not required. There were also [NuGet](https://github.com/tporadowski/redis/tree/develop/msvs/setups/nuget) and [Chocolatey](https://github.com/tporadowski/redis/tree/develop/msvs/setups/chocolatey) packages available (links refer to respective folders in this repo), but so far I have never used those and no-one seemed to be heavily relying on them (at least in a way to even ask about them being updated).

**Comment by OskarPersson** [comment]
```
choco install redis-64
```

followed by 

```
start redis-server
```

worked great, thanks!

**Comment by tporadowski** [comment]
Just please be aware that versions offered by Chocolatey/NuGet are outdated (v3.0.503).
