### ISSUE TITLE
Crash when persistence-available is set to no

### ISSUE THREAD

**Issue by msigley** [tporadowski/redis#52]
The current version 4.0.12.2 crashes when persistence-available is set to no. I am not sure if this option even does anything when you have commented out all of the save lines and set appendonly to no in the config.

**Comment by tporadowski** [comment]
Thanks for reporting this, I've just found this description:
```
# This flag may not be combined with any of the other flags that configure
# AOF and RDB operations.
# persistence-available [(yes)|no]
```
and when I tested just this config directive alone in a config file - it works fine. Could you please share a config that reproduces this issue?

**Comment by msigley** [comment]
You are correct. I misunderstood the docs.
