### ISSUE TITLE
get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by K2ouMais** [tporadowski/redis#60]
I am getting the following error with the newest Redis 5.0.9:

get_magic_quotes_gpc() is deprecated.

I am using the newest Redis 5.0.9 with Laragon and PHP 7.4.6.
The method get_magic_quotes_gpc is deprecated sind PHP 7.4.

![redis](https://user-images.githubusercontent.com/52510455/82936407-d40cc300-9f8e-11ea-99ec-ce3444324cd6.png)

**Comment by Daniel-Mendes** [comment]
It's a problem with phpRedisAdmin not redis, I will send you the fix later

**Comment by K2ouMais** [comment]
You are right. Sorry for this...

Thank you for the fix in advance.

**Comment by Daniel-Mendes** [comment]
They have updated the code to fix this issue: https://github.com/erikdubbelboer/phpRedisAdmin/pull/158

Maybe update your version of phpRedisAdmin in laragon\etc\apps\phpRedisAdmin

Or just delete the deprecated code in includes\common.inc.php see [here](https://github.com/erikdubbelboer/phpRedisAdmin/pull/158/files#diff-0df99719c18011bcb4de0b47297ce91f) the lines to delete.

**Comment by tporadowski** [comment]
@leokhoa was right in his comment to this leokhoa/laragon#174 issue - and helped promote this version more than I would have expected 🤣
