### ISSUE TITLE
Running Redis multiple times on Windows with the same port produces an error

### ISSUE THREAD

**Issue by mehrdadn** [tporadowski/redis#67]
Running Redis twice with the same port works fine on Linux, but produces an error on Windows:

	# Creating Server TCP listening socket *:2048: bind: An operation was attempted on something that is not a socket.

Note that, as per #61, the displayed message does not reflect the true error. The true error is `WSAEADDRINUSE` (or sometimes `WSAEACCESS`, but that itself is [probably this bug](https://support.microsoft.com/en-us/help/3039044/error-10013-wsaeacces-is-returned-when-a-second-bind-to-a-excluded-por) and not relevant).

I tracked this down to the following code in `anet.c` in `_anetTcpServer()`

	if (IF_WIN32(anetSetExclusiveAddr,anetSetReuseAddr)(err,s) == ANET_ERR) goto error;

On Windows, we use an exclusive address/port, but on other platforms we reuse the address/port.

I understand [socket flags are not entirely portable](https://stackoverflow.com/a/14388707), so I'm not sure if this was meant as a workaround for something, or what the best solution might otherwise be, but the inconsistency seems like a bug? I would suggest reverting it to the same behavior as on UNIX systems if it doesn't appear to work around an actual issue. Although, the StackOverflow answer suggests it might be a security issue, so perhaps not? I'm not sure, but I thought I'd raise the issue here.

Thanks!

**Comment by israellot** [comment]
Why would you run two redis instances reusing the port on the same machine? 
Just curious about what use case would that be.

**Comment by tporadowski** [comment]
I've started reading more about it [on MSDN](https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse) and it seems that behavior is non-deterministic, so would also like to know why this should be supported :)

**Comment by mehrdadn** [comment]
It's not really that I expect it to be supported, it's just that I didn't expect the behavior to be different from that on Linux, since that makes it harder to for people (or code) to understand what to do if it happens for whatever reason (even accident).

But actually I seem to have been wrong about that—I just realized, this doesn't work on actual Linux either. Rather, it only "works" on WSL, due to the kernel difference in handling these socket options. So I'll close this issue, sorry for the confusion :) but I guess the takeaway here is WSL might have different behavior in this regard!
