### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Jerry-Shaw** [tporadowski/redis#7]
Thank you so much to push redis to 4.x under windows. Here I met a bug when using it. Paste the detail here, hope it helps.

=== REDIS BUG REPORT START: Cut & paste starting from here ===
Redis version: 4.0.2
[6012] 17 Nov 22:21:25.869 # ------------------------------------------------
[6012] 17 Nov 22:21:25.869 # Fatal Error: decrRefCount against refcount <= 0 #..\src\object.c:328
[6012] 17 Nov 22:21:25.869 # ------------------------------------------------
[6012] 17 Nov 22:21:25.869 # --- EXCEPTION_ACCESS_VIOLATION
[6012] 17 Nov 22:21:25.869 # --- STACK TRACE
redis-server.exe!StackTraceInfo(c:\users\jerry\desktop\redis\src\win32_interop\win32_stacktrace.cpp:153)(0x140163EF0, 0x0014FF90, 0x00000006, 0x0014E9C0)
redis-server.exe!UnhandledExceptiontHandler(c:\users\jerry\desktop\redis\src\win32_interop\win32_stacktrace.cpp:186)(0x14002A690, 0x14002A690, 0x00000006, 0x00000006)
KERNELBASE.dll!UnhandledExceptionFilter(c:\users\jerry\desktop\redis\src\win32_interop\win32_stacktrace.cpp:186)(0x140179EA8, 0x7FFF48BFAE2C, 0x00000000, 0x140046B9D)
ntdll.dll!memset(c:\users\jerry\desktop\redis\src\win32_interop\win32_stacktrace.cpp:186)(0x0014F630, 0x0014EA20, 0x14016A7C0, 0x7FFF47032774)
ntdll.dll!_C_specific_handler(c:\users\jerry\desktop\redis\src\win32_interop\win32_stacktrace.cpp:186)(0x00000000, 0x0014EB30, 0x00000000, 0x00000000)
ntdll.dll!_chkstk(c:\users\jerry\desktop\redis\src\win32_interop\win32_stacktrace.cpp:186)(0x00000000, 0x00000000, 0x0014EF00, 0x00000031)
ntdll.dll!RtlLookupFunctionEntry(c:\users\jerry\desktop\redis\src\win32_interop\win32_stacktrace.cpp:186)(0x7FEC0080C150, 0x140167068, 0x14019CA80, 0x7FFF48AF0F20)
ntdll.dll!KiUserExceptionDispatcher(c:\users\jerry\desktop\redis\src\win32_interop\win32_stacktrace.cpp:186)(0x7FEC00400000, 0x140197CC0, 0x00021260, 0x00008000)
redis-server.exe!_serverPanic(c:\users\jerry\desktop\redis\src\debug.c:661)(0xFFFFFFFFFFFFFFFE, 0x140075011, 0x14019CA80, 0x00000004)
redis-server.exe!decrRefCount(c:\users\jerry\desktop\redis\src\object.c:328)(0x0014FAC8, 0x1401D5ED0, 0xFFFFFFFFFFFFFFFE, 0x04BC0710)
redis-server.exe!sendReplyListDone(c:\users\jerry\desktop\redis\src\networking.c:944)(0x04BC1730, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!aeApiPoll(c:\users\jerry\desktop\redis\src\ae_wsiocp.c:271)(0x00000001, 0x7FEC00000004, 0x20C49BA500000000, 0x20C49BA500000000)
redis-server.exe!aeMain(c:\users\jerry\desktop\redis\src\ae.c:490)(0x02E79300, 0x55E2E729FB4CC, 0x0014FBB9, 0x7FEC008F8000)
redis-server.exe!redis_main(c:\users\jerry\desktop\redis\src\server.c:3966)(0x005651B0, 0x005651B0, 0x00000001, 0x00000000)
redis-server.exe!main(c:\users\jerry\desktop\redis\src\win32_interop\win32_qfork.cpp:1245)(0x00000000, 0x00000000, 0x1401B3C18, 0x00000000)
redis-server.exe!__scrt_common_main_seh(f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk(f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[6012] 17 Nov 22:21:25.916 # --- INFO OUTPUT
# Server
redis_version:4.0.2
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:26c41a2a7714af16
redis_mode:standalone
os:Windows
arch_bits:64
multiplexing_api:WinSock_IOCP
atomicvar_api:pthread-mutex
process_id:6012
run_id:fddf6edb09fb1f458b8497234aa96992ec2191cb
tcp_port:6379
uptime_in_seconds:17
uptime_in_days:0
hz:10
lru_clock:979045
executable:C:\Users\Jerry\Desktop\redis\msvs\x64\Release\redis-server.exe
config_file:

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:691504
used_memory_human:675.30K
used_memory_rss:690488
used_memory_rss_human:674.30K
used_memory_peak:692536
used_memory_peak_human:676.30K
used_memory_peak_perc:99.85%
used_memory_overhead:683626
used_memory_startup:633752
used_memory_dataset:7878
used_memory_dataset_perc:13.64%
total_system_memory:0
total_system_memory_human:0B
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1510928468
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:4
total_commands_processed:1007
instantaneous_ops_per_sec:388
total_net_input_bytes:14143
total_net_output_bytes:17612
instantaneous_input_kbps:5.31
instantaneous_output_kbps:5.87
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:cc1a72c19cf01bc57d95c46338a9c34c076d73eb
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.03
used_cpu_user:0.31
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_pubsub:calls=1,usec=4,usec_per_call=4.00
cmdstat_info:calls=4,usec=863,usec_per_call=215.75
cmdstat_publish:calls=1,usec=7,usec_per_call=7.00
cmdstat_ping:calls=1001,usec=332,usec_per_call=0.33

# Cluster
cluster_enabled:0

# Keyspace
[6012] 17 Nov 22:21:25.916 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by tporadowski** [comment]
Thanks for the report, I've stumbled upon this as well when running redis-benchmark tool for a while.
Related to: #5

**Comment by tporadowski** [comment]
@Jerry-Shaw was there anything specific that caused it? Can you try to reproduce it and write down the steps?

**Comment by Jerry-Shaw** [comment]
I am using test scripts in phpredis to run tests and met this. The first place I met it is running "PubSub" function. Not sure what is going on. But it is OK under 3.2.100.

**Comment by tporadowski** [comment]
@Jerry-Shaw please pull the latest version and try it again then :)

**Comment by Jerry-Shaw** [comment]
@tporadowski Good job. Just tested it. Seems like everything is going well with the latest commit, only few overflows on phpredis extension side. No crash at all.
