### ISSUE TITLE
Cannot disable persistence to RDB

### ISSUE THREAD

**Issue by udofan** [tporadowski/redis#70]
**Describe the bug/issue**
Cannot disable persistence to RDB

**To Reproduce**
1. default release v5.0.9.
2. redis.windows.conf: activate appendonly yes.
3. redis.windows.conf: deactivate rdb commenting save params with #
4. run "redis-server redis.windows.conf"
5. checking config: redis-cli: "config get save" returns ""
5. redis-cli: set k1 value1
6. redis-cli: save
7. dump.rdb was created

**Crash report**
no report was generated

The same problem was in Redis Windows port v3.2.

P.S. And of course I want to thank you for the updated Redis port! Great work!

**Comment by tporadowski** [comment]
I've just checked how it works in Linux version and I'm afraid there is no difference actually. I tried the following:

`save` with empty string:
```
appendonly yes
save ""
```
- AOF file is created and appended to, no changes to RDB are saved unless you explicitly trigger it via `SAVE` - then "dump.rdb" is created

`save` commented out completely:
```
appendonly yes
#save 60 1
```
- same as above.

There is actually no check in call to `rdbSave()` that would prevent the saving of data to a RDB file - first a temporary one is created, then it is renamed to configured file name. I suppose if you don't want to have the RDB created - your only option is to rename `SAVE` and `BGSAVE` commands to something else (see [Disabling of specific commands](https://redis.io/topics/security) chapter), so they cannot be called at all (setting `dbfilename` option to empty still generates that temporary RDB file, but fails at the end when renaming).

I understand that this behavior might not be as one would expect after commenting out `save` option, but I don't want to make an exception here compared to Linux version, especially given that there is a workaround for it.

**Comment by udofan** [comment]
Great answer! Thnx!
