### ISSUE TITLE
Error occured while restarting the sentinel service

### ISSUE THREAD

**Issue by wessisaac** [tporadowski/redis#75]
In Redis on Windows 5.0.9,  Error is occured while restarting the sentinel service.

**Comment by tporadowski** [comment]
@wessisaac please provide more information - what error is reported in Event Log/log file?

**Comment by wessisaac** [comment]
Hi Tomasz,

Thank you very much for your email regarding error details. Please find the
error description / scenario below.

During redis sentinel setup on *Redis on windows 5.0.9, *I am getting the
following error alert on service restart. While starting the service for
the first time we didn't get any issues but on restarting the service or
starting the service for the second time (ie. after the sentinel config
file is converted automatically) we do get the following issue.  The same
setup is working properly in Redis on windows 3.2.1 version.

*Error Alert*:
[image: image.png]

*Error message in event viewer:*
syslog-ident = redis Invalid argument during startup: Could not find
sentinel subcommand known-replica
*Screenshot*:
[image: image.png]

Thanks,
Wesley Isaac.D

**Comment by tporadowski** [comment]
@wessisaac indeed `known-replica` is not supported, but for the moment please use older `known-slave` which should be properly detected in this version.

**Comment by wessisaac** [comment]
tporadowski, how to set known slave? Could you help me.

**Comment by tporadowski** [comment]
Unfortunately it seems that configuration file is rewritten automatically with "known-replica" option, so there is actually no workaround for the moment and I will fix it in next release of 5.0.9

**Comment by tporadowski** [comment]
Fixed in 3144475

**Comment by wessisaac** [comment]
Thank you tporadowski.
