### ISSUE TITLE
CLIENT LIST command doesn't support TYPE argument

### ISSUE THREAD

**Issue by mrniko** [tporadowski/redis#78]
**Describe the bug/issue**
[CLIENT LIST](https://redis.io/commands/client-list) command doesn't support TYPE argument which is supported as of 5.0 version

**To Reproduce**
type CLIENT LIST NORMAL

**INFO output**
ERR syntax error

**Additional context**
Redis for windows 5.0.9

**Comment by tporadowski** [comment]
@mrniko thanks for the report, but it works according to the specification, which states:

> As of v5.0, the optional `TYPE type` subcommand can be used to filter the list by clients' type, where type is one of _normal_, _master_, _replica_ and _pubsub_.

This might indeed be a bit misleading (and there are no examples with this subcommand either in the docs), but it must be sent as `CLIENT LIST TYPE NORMAL` (**TYPE** keyword is required).

**Comment by tporadowski** [comment]
Example:
```
127.0.0.1:6379> client list type normal
id=3 addr=127.0.0.1:54796 fd=9 name= age=285 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=48 qbuf-free=32720 obl=0 oll=0 omem=0 events=r cmd=client
127.0.0.1:6379> client list type master
127.0.0.1:6379> client list type replica
127.0.0.1:6379> client list type pubsub
127.0.0.1:6379> client list type test
ERR Unknown client type 'test'
127.0.0.1:6379> client list missing_type
ERR syntax error
```

**Comment by mrniko** [comment]
Right! Sorry, my mistake. Thank you for you time!
