### ISSUE TITLE
怎么没找到win32位的

### ISSUE THREAD

**Issue by melodyne** [tporadowski/redis#86]
**Describe the bug/issue**
A clear and concise description of what the bug/issue is.

**To Reproduce**
Please provide more information about:
- version of Redis for Windows you are using
- configuration of your instance if it's not out-of-the-box one (i.e. persistence type)
- typical workload handled by your instance
- any other details that might be helpful in reproducing the issue.

**Crash report**
If Redis generated a crash report - please paste it here.

**INFO output**
If possible - please provide output of `INFO` command that might be helpful in analyzing your issue.

**Event Log**
Please check your system's Event Log to see if there are additional details logged related to this issue.

**Additional context**
Please provide Windows version you are using, mode in which you are starting Redis (standalone, cluster, Sentinel), etc.

**Comment by tporadowski** [comment]
Google translate suggests you are asking about Win32 version - there isn't one. Original statement from MSOpenTech team who worked on this port of Redis:

> We officially support the 64-bit version only. Although you can build the 32-bit version from source if desired.

Personally I have not even tried to build it yet.

**Comment by melodyne** [comment]
在网上找了很久才找到一个3.x老版本，真希望能提win32支持，非常感谢！
