### ISSUE TITLE
Critical memory leak when working with redis stream and more then 3 consumers

### ISSUE THREAD

**Issue by awaizman1** [tporadowski/redis#87]
**Intro**
When working with redis streams with 3 consumers or more in a consumer group, the memory usage keeps increasing until OOM. The same doesn't happen in linux.

**Details**
I wrote a simple task distribution using redis streams. For this I have a single client which produce/add tasks to ```req_strm``` stream. A bunch of worker processes join a single workers consumer group and read tasks from the ```req_strm``` stream. Once a task is read by a worker it is immediately deleted from the ```req_strm``` stream. In addition, per read task the worker writes/adds to another ```res_strm``` stream a response.
The client reads a response for each submitted task from the res_strm stream.

Test flow:
1. run 3 workers processes - each process:
    - reads from res_strm
    - delete read task from res_strm
    - send response to res_strm.
2. run a single client process - endless loop, per iteration:
    - submit 10K tasks to req_strm
    - read 10K responses from res_strm
    - delete all elements in res_strm
    - print iteration statistics (including redis used memory)

The used memory should be steady since by the end of each iteration both ```req_strm``` and ```res_strm``` are empty. This is the case when running 1 or 2 workers but when running 3 or more workers the used memory keeps increasing until I get OOM.
I run the same on linux and memory usage is stable as expected.

**To Reproduce**
Please provide more information about:
- Redis for Windows: 5.0.9
- configuration modifications:
   - snapshotting disabled
   - persistence-available no
   - maxmemory 100000000 (to get OOM)
   - maxmemory-policy noeviction (to get OOM)
- Windows 10
- python client and worker:
   - python 3.6.8
   - redis 3.5.3 [py redis client](https://pypi.org/project/redis/)

**Test code:**
to run a worker: ```python test_redis.py w```
to run the client: ```python test_redis.py```
```python
import os
import sys
import time

import redis

r = redis.Redis(host='localhost', port=6379)
REQUEST_STRM = 'req_strm'
RESPONSE_STRM = 'res_strm'


def client():

    r.xtrim(REQUEST_STRM, 0)
    r.xtrim(RESPONSE_STRM, 0)

    iter = 1
    while True:
        start = time.time()

        redis_id = 0
        # submit 10k tasks
        for i in range(10000):
            r.xadd(REQUEST_STRM, fields={'task_id': i})

        # get 10K responses
        for i in range(10000):
            r.xread({RESPONSE_STRM: redis_id}, count=1, block=0)

        # trim res_strm
        r.xtrim(RESPONSE_STRM, 0)

        end = time.time()

        print(f'=========== Iteration {iter} Summary ============')
        print(f'took {end - start:.2} sec')
        print(f'request strm length: {r.xlen(REQUEST_STRM)}, response strm length: {r.xlen(RESPONSE_STRM)}')
        print('used_memory_human:', r.info('memory')['used_memory_human'])

        iter += 1


def worker():

    worker_name = f'worker_{os.getpid()}'

    # create consumer group (ignored if already exists since can already created by another worker)
    try:
        r.xgroup_create(REQUEST_STRM, 'workers', id=0, mkstream=True)
    except:
        pass

    count = 0
    while True:

        # read a task
        ret = r.xreadgroup('workers', worker_name, streams={REQUEST_STRM: '>'}, count=1, block=0, noack=True)
        redis_id = ret[0][1][0][0]
        task_id = ret[0][1][0][1][b'task_id']

        # delete the task from req_strm and send response to res_strm
        p = r.pipeline()
        p.xdel(REQUEST_STRM, redis_id)
        p.xadd(RESPONSE_STRM, {'task_id': task_id})
        p.execute()

        count += 1
        if count % 1000 == 0:
            print('handled', count / 1000, 'K tasks')


if __name__ == '__main__':

    if len(sys.argv) > 1 and sys.argv[1] == 'w':
        print('running as worker')
        worker()
    else:
        print('running as client')
        client()

```

Will be glad to provide more info or run more tests.

Thanks.

**Comment by tporadowski** [comment]
Thanks for such a great report and all the details! I will try to run that test case on my end and see what is happening.

**Comment by awaizman1** [comment]
Hi @tporadowski,

I keep investigating this issue too and have an update:
when the worker acknowledge the task using ```xack``` the memory consumption is stable. but when using ```NOACK``` option in the ```xreadgroup``` command (and not doing ```xack```) the memory leaks.

I'll try compare the stream src code to the linux redis one and see if there are differences there.
will keep u updated.

**Comment by awaizman1** [comment]
Hi @tporadowski,

It seems like a bug in redis 5.0.9 and not specific to the windows port.
Wrongly I run 5.0.10 in linux and saw the memory is stable, but when runnin 5.0.9 in linux the issue reproduces.
I also took t_stream.c and stream.h from redis 5.0.10 and patched the one in win redis 5.0.9 and the problem seems to be solved (no leak).

I there a chance you could release win redis based on 5.0.10? Although I can take win 5.0.9 and patch stream files from redis 5.0.10 and build, I prefer relay on your builds and releases.

Sorry for the mistake of comparing win redis 5.0.9 with linux redis 5.0.10.

Thanks.

**Comment by tporadowski** [comment]
Great, thanks for checking against that latest release. I've seen 5.0.10 has been released recently, so yes - I plan to release it too, but it might take a week or two (I haven't checked yet in depth what has been fixed there).

**Comment by tporadowski** [comment]
@awaizman1 the list of changes in 5.0.10 wasn't that long, so I managed to port them to [win-5.0 branch](https://github.com/tporadowski/redis/tree/win-5.0). I am however struggling a bit with passing `unit/memefficiency` test, which as far as I remember - was fine before releasing 5.0.9.

**Comment by tporadowski** [comment]
[Redis 5.0.10 for Windows](https://github.com/tporadowski/redis/releases/tag/v5.0.10) has just been released.

**Comment by awaizman1** [comment]
@tporadowski 

Thanks a lot!
