### ISSUE TITLE
No binary

### ISSUE THREAD

**Issue by Kortenbach** [tporadowski/redis#9]
Hi,

I'm very happy that someone took the challenge and started this new Redis fork!
I am sorry to call this an issue, but I'm sure many Windows users would like to be able to download an  .exe file from somewhere. Maybe someone can provide a link or something like that?

At the moment I am  still using the Microsoft fork, but it has some issues, so I would like to test-drive this version to see how it behaves!

**Comment by tporadowski** [comment]
Hi @Kortenbach you can download an installer and ZIP package from **Releases** tab - https://github.com/tporadowski/redis/releases/tag/v4.0.2-alpha

Regards,
Tomasz

**Comment by Kortenbach** [comment]
Thanks! I'm sorry I missed that.
Will try right now!
