### ISSUE TITLE
Bug Report : Redis crashes intermittently - EXCEPTION_INT_DIVIDE_BY_ZERO

### ISSUE THREAD

**Issue by 212588083** [tporadowski/redis#91]
**Describe the bug/issue**
Using Redis version 3.0.504 and the service crashes periodically on the server. 

**To Reproduce**
Please provide more information about:
- version of Redis : 3.0.504
- Windows server 2016 
- There are no specific steps to reproduce but the Redis crashes periodically from time to time.

**Crash report**
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[14584] 15 Nov 15:44:51.634 # Redis version: 3.0.504
[14584] 15 Nov 15:44:51.634 # --- EXCEPTION_INT_DIVIDE_BY_ZERO
[14584] 15 Nov 15:44:51.634 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x00F6E690, 0x00F6FF90, 0x00000001, 0x401248B0)
redis-server.exe!UnhandledExceptiontHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x00000000, 0x00000000, 0x94FF14AF, 0x00000001)
KERNELBASE.dll!UnhandledExceptionFilter(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x00F6EE00, 0xC0B41E08, 0x00000000, 0x40065C23)
ntdll.dll!memset(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x00F6F2F0, 0x00000001, 0xBDFA84D4, 0x00F6FAF0)
ntdll.dll!_C_specific_handler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x00000000, 0x00F6E800, 0x00F6EE00, 0x00000000)
ntdll.dll!_chkstk(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0xBE044498, 0x00F6EE00, 0x00000000, 0x400ADD77)
ntdll.dll!RtlImageNtHeaderEx(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x00000000, 0x00000000, 0x00F6F4E0, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x00008301, 0x02C070A0, 0x00000000, 0x00F6F4E0)
redis-server.exe!rioFileWrite(c:\release\redis\src\rio.c:118)(0x00000009, 0x00F6F4E0, 0x00000009, 0x00000006)
redis-server.exe!rdbSaveRio(c:\release\redis\src\rdb.c:673)(0x40150210, 0x02D05000, 0x00000016, 0x02C070A0)
redis-server.exe!rdbSave(c:\release\redis\src\rdb.c:758)(0x020F4440, 0x00000007, 0x02D05000, 0x400AB79F)
redis-server.exe!saveCommand(c:\release\redis\src\rdb.c:1583)(0x00000000, 0x2A7A1BD6, 0x02C090A0, 0x4008E95C)
redis-server.exe!call(c:\release\redis\src\redis.c:2122)(0x5FB19343, 0x400A5AE0, 0x00000000, 0x00000016)
redis-server.exe!processCommand(c:\release\redis\src\redis.c:2368)(0x00000004, 0x00000016, 0x00000000, 0x00000000)
redis-server.exe!processInputBuffer(c:\release\redis\src\networking.c:1291)(0x00000000, 0x00000016, 0x0000000E, 0x00000000)
redis-server.exe!readQueryFromClient(c:\release\redis\src\networking.c:1344)(0x02C6F2C0, 0x00000001, 0x02C4B150, 0x000001A4)
redis-server.exe!aeMain(c:\release\redis\src\ae.c:481)(0x5FADC5D8, 0x02C06FA8, 0x00000002, 0x00550240)
redis-server.exe!redis_main(c:\release\redis\src\redis.c:3765)(0x00000000, 0x00508780, 0x5FADC5D8, 0x00508780)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1237)(0x00000016, 0xFFFFFFFF, 0x00000016, 0x00000000)
redis-server.exe!ServiceWorkerThread(c:\release\redis\src\win32_interop\win32_service.cpp:484)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk(c:\release\redis\src\win32_interop\win32_service.cpp:484)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:484)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:484)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[14584] 15 Nov 15:44:51.634 # --- INFO OUTPUT
# Server
redis_version:3.0.504
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:a4f7a6e86f2d60b3
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:14584
run_id:0623882ed63d0464bc082f8d4d5f8eed4f96a828
tcp_port:6379
uptime_in_seconds:249195
uptime_in_days:2
hz:10
lru_clock:11637571
config_file:C:\Program Files\Redis\redis.windows-service.conf

# Clients
connected_clients:16
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:1008952
used_memory_human:985.30K
used_memory_rss:1008048
used_memory_peak:1348280
used_memory_peak_human:1.29M
used_memory_lua:36864
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:490
rdb_bgsave_in_progress:0
rdb_last_save_time:1605223896
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:83
total_commands_processed:67733
instantaneous_ops_per_sec:3
total_net_input_bytes:3575727
total_net_output_bytes:7912239
instantaneous_input_kbps:0.18
instantaneous_output_kbps:0.34
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:65
evicted_keys:0
keyspace_hits:1029
keyspace_misses:71
pubsub_channels:3
pubsub_patterns:7
latest_fork_usec:0
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.06
used_cpu_user:0.09
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_get:calls=745,usec=1649,usec_per_call=2.21
cmdstat_set:calls=35,usec=780,usec_per_call=22.29
cmdstat_setex:calls=86,usec=2047,usec_per_call=23.80
cmdstat_del:calls=4127,usec=4607,usec_per_call=1.12
cmdstat_exists:calls=645,usec=1215,usec_per_call=1.88
cmdstat_expire:calls=355,usec=7593,usec_per_call=21.39
cmdstat_ping:calls=30784,usec=74990,usec_per_call=2.44
cmdstat_echo:calls=16,usec=10,usec_per_call=0.63
cmdstat_flushall:calls=1,usec=12,usec_per_call=12.00
cmdstat_info:calls=30829,usec=609925,usec_per_call=19.78
cmdstat_slaveof:calls=4,usec=407,usec_per_call=101.75
cmdstat_config:calls=57,usec=1943,usec_per_call=34.09
cmdstat_subscribe:calls=17,usec=58,usec_per_call=3.41
cmdstat_psubscribe:calls=8,usec=32,usec_per_call=4.00
cmdstat_cluster:calls=8,usec=9,usec_per_call=1.13
cmdstat_client:calls=16,usec=32,usec_per_call=2.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0
[14584] 15 Nov 15:44:51.634 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Event Log**
Source: Time-Service
11/15/2020 3:44:24 PM The time provider NtpClient is currently receiving valid time data from time.windows.com,0x8 (ntp.m|0x8|0.0.0.0:123->13.86.101.172:123).
Source: Service Control Manager
11/15/2020 3:44:51 PM The Windows Error Reporting Service service entered the running state.
11/15/2020 3:44:51 PM The Redis service terminated unexpectedly.  It has done this 1 time(s).

[redis.windows-service.zip](https://github.com/tporadowski/redis/files/5560935/redis.windows-service.zip)

**Comment by tporadowski** [comment]
Please try one of the newer versions - 4.0.14.2 or 5.0.10 as I am not supporting 3.x
